### PR TITLE
feat: Implement the settings page

### PR DESCRIPTION
**Pull request by outloudvi**
Currently only language selection is on there.

Also, this PR comes with a passing-by fix on adding keys to event/gacha list (8450466), which shall help improve the stability and reduce console warnings.

### CODE REVIEW

**Comment by outloudvi** [comment]
Also, I'd like to request for your opinion on the localization module. Currently D4DB is using a hand-written l10n module - which shall be okay - and a flat layout of strings - which might be a little messy in the future. Due to the increasing amount of l10n strings, I'm thinking of using a leveled localization string organization to make the string list clear, for example:

``` js
  // ...
  HOME: {
    TITLE: 'Home',
    ONGOING_EVENT: 'Ongoing Event',
    ONGOING_GACHA: 'Ongoing Gacha',
    NEWS: 'News',
    OFFICIAL_TWITTER: 'Official Twitter Account',
    NO_EVENTS: 'No events ongoing',
    NO_GACHAS: 'No gacha banners ongoing',
  },
  // ...
```

And it can be used in the following way:

``` js
strings.getString("HOME.NO_GACHAS") // -> No gacha banners ongoing
```

I've implemented it at [`feat/leveled-l10n`](https://github.com/outloudvi/D4DB/tree/feat/leveled-l10n), and if you also think it's okay, I'll land that on the PR of attempting to get more strings l10n covered.

**Review by RayFirefist — COMMENTED** [review]
Those changes are really good to me. Settings page I kind of wanted to also enable the page since I planned to have it kinda complex, but as modal for now is also fine, since there is only to swap languages

**Comment by RayFirefist** [comment]
> Also, I'd like to request for your opinion on the localization module. Currently D4DB is using a hand-written l10n module - which shall be okay - and a flat layout of strings - which might be a little messy in the future. Due to the increasing amount of l10n strings, I'm thinking of using a leveled localization string organization to make the string list clear [...]

I agree with that. However, I kind of wanted to keep the l10n files as JSON (at least, I hope that JS code was an example) because they look kinda easier to edit for everyone (despite of I found out that JSONs are not that user friendly for whoever never approached them-)

**Comment by outloudvi** [comment]
JSON is indeed less friendly than JS for its requirement of double quotes (`"`), and also not allowing comments (usually).

So I got your idea of keeping the translation strings in a flat layout for now. Also, it would be beneficial to add a message instructing the location of all translation string files.

**Comment by RayFirefist** [comment]
> JSON is indeed less friendly than JS for its requirement of double quotes (`"`), and also not allowing comments (usually).
> 
> So I got your idea of keeping the translation strings in a flat layout for now. Also, it would be beneficial to add a message instructing the location of all translation string files.

Fine to me. I will add later guideline for translations. I edited a string because it didn't look correct to me for that context (the "Quit" on modal)

**Comment by outloudvi** [comment]
> I edited a string because it didn't look correct to me for that context (the "Quit" on modal)

Seems better! I actually thought about which word to use in there for a really good while :laughing:

**Comment by RayFirefist** [comment]
Going to merge the changes, thanks!
I'm going to make some commits for some bug fix and version increase, so make sure to pull first once my commits will be up

**Pull request merged**
