### PR TITLE
feat: simplified Chinese translation

### PR DESCRIPTION
**Pull request by outloudvi**
I really appreciate your project :) There are several strings that I didn't translate due to concerns:
* `MAIN_CATEGORY_TITLE` - Didn't see any use of it.
* `COMMON_ATTRIBUTE_1/2/3/4/5` - Seems unnecessary to translate card categories.
* `EVENT_RECEPTION_CLOSE_DATE` - What does it mean? Is it impossible to take part in an event if there is not scoring after that time?
* `CARDS_ILLUST_PREMIUM` - Didn't see a card example with this. Could you give an example with Premium card so that I can get more details?

The translations are partially inspired by <https://bandori.top> and <https://sekai.best>.

### CODE REVIEW

**Comment by RayFirefist** [comment]
- `CARDS_ILLUST_PREMIUM` is the animated 4 star card. Right now it's a placeholder since I don't really know how to make it usable on website.
- `EVENT_RECEPTION_CLOSE_DATE` should be the time when the event closes and you can't earn more points. This comes earlier than the event actually disappears from the game
- `COMMON_ATTRIBUTE_1/2/3/4/5` apparently every chinese translated mobage I know they don't translate in chinese the attributes, so it makes sense and I agree
- `MAIN_CATEGORY_TITLE ` I should recheck that, since I don't actually remember about this.

Thank you so much for your contribution!

**Comment by outloudvi** [comment]
Thanks for your reply! I updated `CARDS_ILLUST_PREMIUM` and `EVENT_RECEPTION_CLOSE_DATE` according to your messages. Now I don't think I have expanded concerns on the scope of this PR.

> * `CARDS_ILLUST_PREMIUM` is the animated 4 star card. Right now it's a placeholder since I don't really know how to make it usable on website.

I got your idea - I've got a Birthday card for Towa Hanamaki and I guess you are indicating that type of animated card.

It seems that there are some other untranslated strings (e.g. character names, music categories/difficulties), and - if you don't mind - I'll try to make another PR to get them also translated.

**Comment by RayFirefist** [comment]
> It seems that there are some other untranslated strings (e.g. character names, music categories/difficulties), and - if you don't mind - I'll try to make another PR to get them also translated.

Character names and categories are actually provided from website API from game's database. I'd need to rework a bit the code in order to have the possibility to translate those things.

**Comment by outloudvi** [comment]
> Character names and categories are actually provided from website API from game's database. I'd need to rework a bit the code in order to have the possibility to translate those things.

Since they are relatively stable, I think it's just enough to try to match existing strings on the front-end part, and fallback to original ones if it's unseen before. It would be simpler to leave the flexibility on the front-end.

**Comment by RayFirefist** [comment]
This project is open to everyone's contribution. Plus, you (and I) can see on live the online preview of every commit easily and automatically (this thanks to Vercel lol).
If you want to implement it, feel free to do that and I'll merge it into the main branch and publish it

**Comment by outloudvi** [comment]
Okay, I'll do that.
Would you like to merge this PR, so that there will be no need to resolve conflicts for the forementioned PR, since apperently I also have to update `zh-hans.json` for that?
Or would you prefer my also doing that on this PR?

**Comment by RayFirefist** [comment]
> Would you like to merge this PR, so that there will be no need to resolve conflicts for the forementioned PR, since apperently I also have to update `zh-hans.json` for that?

If you can confirm that you are done for translations for now I'll close the pull request and merge it. For that you can open an another PR once you have something done

**Comment by outloudvi** [comment]
Yes, I've finished in the scope of this PR.

**Comment by outloudvi** [comment]
I realized a problem I was thinking of but forgot afterwards. Since `EVENT_RECEPTION_CLOSE_DATE` is the point when score stop accumulating, what's the difference between this and `EVENT_RANK_FIX_START_DATE`? Seems that the latter one has the same meaning.

**Pull request merged**
